package models;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import utils.DBConnect;

public class User {
    private Integer userId;
    private String name;
    private String email;
    private String password;
    private Date dob;
    private Character gender; // 'M' or 'F'
    private String address;
    private City city;
    private String contact;
    private String profilePic;
    private Status status;
    private String activationCode;


    // ################## Methods ##################
    public String getUserFolder(){
        if(userId == null)throw new RuntimeException("User Folder : user Id not Exists");
        String path = "WEB-INF/uploads/user_" + this.userId;
        return path;
    }

    // ---------------constructors--------------------------
    public User() {
        
    }

    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public User(String name, String email, String password, City city, String contact) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.city = city;
        this.contact = contact;
    }

    //******************login method start***************************
    public void loginUser() {
        status = new Status(-1); // email not match...

        try {
            Connection con = DBConnect.getConnection();

            // String query = "select * from users where email=?";
            // String query = "SELECT u.*, c.city, s.state FROM users u INNER JOIN cities c ON u.city_id = c.city_id INNER JOIN states s ON c.state_id = s.state_id WHERE u.email = ?";
            // String query = "SELECT u.*, c.city_id, c.city, s.state_id, s.state FROM users u INNER JOIN cities c ON u.city_id = c.city_id INNER JOIN states s ON c.state_id = s.state_id WHERE u.email = ?";
            String query = "SELECT u.*, c.city_id, c.city, s.state_id, s.state, t.status_id, t.status FROM users u INNER JOIN cities c ON u.city_id = c.city_id INNER JOIN states s ON c.state_id = s.state_id INNER JOIN status t ON u.status_id = t.status_id WHERE u.email = ?";

            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, email);
            // ps.setString(2, password);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                if (password.equals(rs.getString("password"))) {
                    userId = rs.getInt("user_id");
                    name = rs.getString("name");
                    dob = rs.getDate("dob");
                    String genderstr = rs.getString("gender");
                    gender = (genderstr != null && !genderstr.isEmpty()) ? genderstr.charAt(0) : null;

                    // gender = rs.getString("gender").charAt(0);
                    address = rs.getString("address");
                    // city = new City(rs.getInt("city_id"));

                    State state = new State(rs.getInt("state_id"), rs.getString("state"));
                    city = new City(rs.getInt("city_id"), rs.getString("city"), state);

                    contact = rs.getString("contact");
                    profilePic = rs.getString("profile_pic");
                    status = new Status(rs.getInt("u.status_id"), rs.getString("t.status"));
                } else {
                    status = new Status(0); // incorrect password
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    //******************login method end***************************

    //******************signup method start***************************
    public boolean signUpUser() {
        boolean flag = false;

        try {
            Connection con = DBConnect.getConnection();

            if (con != null) {
                String query = "insert into users (name,email,password,city_id,contact) value (?,?,?,?,?)";

                PreparedStatement ps = con.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS);

                ps.setString(1, name);
                ps.setString(2, email);
                ps.setString(3, password);
                ps.setInt(4, city.getCityId());
                ps.setString(5, contact);

                int res = ps.executeUpdate();

                if (res == 1) {
                    ResultSet generatedKeys = ps.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        userId = generatedKeys.getInt(1); // Set the autogenerated userId
                    }
                    flag = true;
                }

                con.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return flag;
    }
    //******************signup method end***************************
    
    //******************getter & setter methods start***************************
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public Date getDob() {
        return dob;
    }

    public void setGender(Character gender) {
        this.gender = gender;
    }

    public Character getGender() {
        return gender;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return address;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public City getCity() {
        return city;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getContact() {
        return contact;
    }

    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    public String getProfilePic() {
        return profilePic;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Status getStatus() {
        return status;
    }

    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }

    public String getActivationCode() {
        return activationCode;
    }
    //******************getter & setter methods end***************************
}